### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SophieV** [josephdburdick/Git-Workflow#1]
Hey Joe, I still have some open questions that I would like to clarify. Thanks for your help !

Let's say a bunch of people are working on a given featureName.

From the documentation, I understood : we have master branch ; we create featureName branch ; and each one of us working on the feature uses the own username/featureName branch until ready to be merged to featureName branch. And we could rebase with otherUsername/featureName if that collaboration is needed.
- From your description it sounded like we use directly username/featureName without a "common" featureName branch ?

We should regularly sync our own username/featureName branch with featureName branch (or master ?) to make sure our progress is not going to create conflicts.
- Please confirm or discuss whether this is what helps preventing the merge conflicts.
  I understand how rebase helps keeping the history logs clean. What is not clear is how using rebase is reducing the conflicts. If several persons work on the same code piece in different branches (their own username/featureName), how does it make any difference compared to using the git merge command.

**Comment by josephdburdick** [comment]
Thanks for posting your Qs here, @SophieV.

> From your description it sounded like we use directly username/featureName without a "common" featureName branch ?

Nah, you can have shared branches. Sharing a branch is completely fine, but it can only be merged to from your own, unique branch. 

For example, let's say you have a branch called **dev**– pretty common to have multiple developers hitting such a branch. The **dev** branch has 3 developers: Joe, Sofi, and Bill. They all want to have a branch to test new features on before submitting to **master** because master auto-deploys to the live site. They should all have their own branches for their own work and rebasing, and, if juggling many tasks/branches, the branch they use to merge with **dev** should be called bill/dev, sofi/dev, etc.

The _username/branch-name_ convention has a number of benefits including:
1. easing branch maintenance by knowing when a branch is yours after large amounts of time has passed
2. demystifying when it's completely okay to rewrite history when you have complex branches 

> We should regularly sync our own username/featureName branch with featureName branch (or master ?) to make sure our progress is not going to create conflicts.

If multiple people are working on the same feature/fix, feel free to rebase your branch with the shared branch often. Or don't. It doesn't really matter as long as you do it before merging your branch into master, but **if another developer touches the same line in the same file as you you may need to resolve a conflict while rebasing**. This will happen now or later, the preference as to when to handle it is up to you. Rebasing places your work on top of the branch being rebased and because you must rebase before merging there is no defined moment to handle it as long as you follow the process correctly. Rebasing prevents conflicts by bringing your branch up to date with another and placing your changes on top. 

Conflict prevention with this technique is not a guarantee, but it does happen a lot less and it also enforces great documentation on the master/shared branches and it also reinforces backups on individual branches.
